/// All world countries with flag emojis, ISO codes, dial codes, and currencies.
/// Source: ISO 3166-1 — 195 sovereign states + dependent territories.
class WorldCountries {
  WorldCountries._();

  static const List<Map<String, String>> all = [
    {'name': 'Afghanistan', 'code': 'AF', 'flag': '🇦🇫', 'dialCode': '+93', 'currency': 'AFN'},
    {'name': 'Åland Islands', 'code': 'AX', 'flag': '🇦🇽', 'dialCode': '+358', 'currency': 'EUR'},
    {'name': 'Albania', 'code': 'AL', 'flag': '🇦🇱', 'dialCode': '+355', 'currency': 'ALL'},
    {'name': 'Algeria', 'code': 'DZ', 'flag': '🇩🇿', 'dialCode': '+213', 'currency': 'DZD'},
    {'name': 'American Samoa', 'code': 'AS', 'flag': '🇦🇸', 'dialCode': '+1684', 'currency': 'USD'},
    {'name': 'Andorra', 'code': 'AD', 'flag': '🇦🇩', 'dialCode': '+376', 'currency': 'EUR'},
    {'name': 'Angola', 'code': 'AO', 'flag': '🇦🇴', 'dialCode': '+244', 'currency': 'AOA'},
    {'name': 'Anguilla', 'code': 'AI', 'flag': '🇦🇮', 'dialCode': '+1264', 'currency': 'XCD'},
    {'name': 'Antarctica', 'code': 'AQ', 'flag': '🇦🇶', 'dialCode': '+672', 'currency': 'USD'},
    {'name': 'Antigua & Barbuda', 'code': 'AG', 'flag': '🇦🇬', 'dialCode': '+1268', 'currency': 'XCD'},
    {'name': 'Argentina', 'code': 'AR', 'flag': '🇦🇷', 'dialCode': '+54', 'currency': 'ARS'},
    {'name': 'Armenia', 'code': 'AM', 'flag': '🇦🇲', 'dialCode': '+374', 'currency': 'AMD'},
    {'name': 'Aruba', 'code': 'AW', 'flag': '🇦🇼', 'dialCode': '+297', 'currency': 'AWG'},
    {'name': 'Australia', 'code': 'AU', 'flag': '🇦🇺', 'dialCode': '+61', 'currency': 'AUD'},
    {'name': 'Austria', 'code': 'AT', 'flag': '🇦🇹', 'dialCode': '+43', 'currency': 'EUR'},
    {'name': 'Azerbaijan', 'code': 'AZ', 'flag': '🇦🇿', 'dialCode': '+994', 'currency': 'AZN'},
    {'name': 'Bahamas', 'code': 'BS', 'flag': '🇧🇸', 'dialCode': '+1242', 'currency': 'BSD'},
    {'name': 'Bahrain', 'code': 'BH', 'flag': '🇧🇭', 'dialCode': '+973', 'currency': 'BHD'},
    {'name': 'Bangladesh', 'code': 'BD', 'flag': '🇧🇩', 'dialCode': '+880', 'currency': 'BDT'},
    {'name': 'Barbados', 'code': 'BB', 'flag': '🇧🇧', 'dialCode': '+1246', 'currency': 'BBD'},
    {'name': 'Belarus', 'code': 'BY', 'flag': '🇧🇾', 'dialCode': '+375', 'currency': 'BYN'},
    {'name': 'Belgium', 'code': 'BE', 'flag': '🇧🇪', 'dialCode': '+32', 'currency': 'EUR'},
    {'name': 'Belize', 'code': 'BZ', 'flag': '🇧🇿', 'dialCode': '+501', 'currency': 'BZD'},
    {'name': 'Benin', 'code': 'BJ', 'flag': '🇧🇯', 'dialCode': '+229', 'currency': 'XOF'},
    {'name': 'Bermuda', 'code': 'BM', 'flag': '🇧🇲', 'dialCode': '+1441', 'currency': 'BMD'},
    {'name': 'Bhutan', 'code': 'BT', 'flag': '🇧🇹', 'dialCode': '+975', 'currency': 'BTN'},
    {'name': 'Bolivia', 'code': 'BO', 'flag': '🇧🇴', 'dialCode': '+591', 'currency': 'BOB'},
    {'name': 'Bosnia & Herzegovina', 'code': 'BA', 'flag': '🇧🇦', 'dialCode': '+387', 'currency': 'BAM'},
    {'name': 'Botswana', 'code': 'BW', 'flag': '🇧🇼', 'dialCode': '+267', 'currency': 'BWP'},
    {'name': 'Bouvet Island', 'code': 'BV', 'flag': '🇧🇻', 'dialCode': '+47', 'currency': 'NOK'},
    {'name': 'Brazil', 'code': 'BR', 'flag': '🇧🇷', 'dialCode': '+55', 'currency': 'BRL'},
    {'name': 'British Indian Ocean Territory', 'code': 'IO', 'flag': '🇮🇴', 'dialCode': '+246', 'currency': 'USD'},
    {'name': 'Brunei Darussalam', 'code': 'BN', 'flag': '🇧🇳', 'dialCode': '+673', 'currency': 'BND'},
    {'name': 'Bulgaria', 'code': 'BG', 'flag': '🇧🇬', 'dialCode': '+359', 'currency': 'BGN'},
    {'name': 'Burkina Faso', 'code': 'BF', 'flag': '🇧🇫', 'dialCode': '+226', 'currency': 'XOF'},
    {'name': 'Burundi', 'code': 'BI', 'flag': '🇧🇮', 'dialCode': '+257', 'currency': 'BIF'},
    {'name': 'Cambodia', 'code': 'KH', 'flag': '🇰🇭', 'dialCode': '+855', 'currency': 'KHR'},
    {'name': 'Cameroon', 'code': 'CM', 'flag': '🇨🇲', 'dialCode': '+237', 'currency': 'XAF'},
    {'name': 'Canada', 'code': 'CA', 'flag': '🇨🇦', 'dialCode': '+1', 'currency': 'CAD'},
    {'name': 'Cape Verde', 'code': 'CV', 'flag': '🇨🇻', 'dialCode': '+238', 'currency': 'CVE'},
    {'name': 'Cayman Islands', 'code': 'KY', 'flag': '🇰🇾', 'dialCode': '+1345', 'currency': 'KYD'},
    {'name': 'Central African Republic', 'code': 'CF', 'flag': '🇨🇫', 'dialCode': '+236', 'currency': 'XAF'},
    {'name': 'Chad', 'code': 'TD', 'flag': '🇹🇩', 'dialCode': '+235', 'currency': 'XAF'},
    {'name': 'Chile', 'code': 'CL', 'flag': '🇨🇱', 'dialCode': '+56', 'currency': 'CLP'},
    {'name': 'China', 'code': 'CN', 'flag': '🇨🇳', 'dialCode': '+86', 'currency': 'CNY'},
    {'name': 'Christmas Island', 'code': 'CX', 'flag': '🇨🇽', 'dialCode': '+61', 'currency': 'AUD'},
    {'name': 'Cocos (Keeling) Islands', 'code': 'CC', 'flag': '🇨🇨', 'dialCode': '+61', 'currency': 'AUD'},
    {'name': 'Colombia', 'code': 'CO', 'flag': '🇨🇴', 'dialCode': '+57', 'currency': 'COP'},
    {'name': 'Comoros', 'code': 'KM', 'flag': '🇰🇲', 'dialCode': '+269', 'currency': 'KMF'},
    {'name': 'Congo (Brazzaville)', 'code': 'CG', 'flag': '🇨🇬', 'dialCode': '+242', 'currency': 'XAF'},
    {'name': 'Congo (Kinshasa)', 'code': 'CD', 'flag': '🇨🇩', 'dialCode': '+243', 'currency': 'CDF'},
    {'name': 'Cook Islands', 'code': 'CK', 'flag': '🇨🇰', 'dialCode': '+682', 'currency': 'NZD'},
    {'name': 'Costa Rica', 'code': 'CR', 'flag': '🇨🇷', 'dialCode': '+506', 'currency': 'CRC'},
    {'name': "Côte d'Ivoire", 'code': 'CI', 'flag': '🇨🇮', 'dialCode': '+225', 'currency': 'XOF'},
    {'name': 'Croatia', 'code': 'HR', 'flag': '🇭🇷', 'dialCode': '+385', 'currency': 'EUR'},
    {'name': 'Cuba', 'code': 'CU', 'flag': '🇨🇺', 'dialCode': '+53', 'currency': 'CUP'},
    {'name': 'Cyprus', 'code': 'CY', 'flag': '🇨🇾', 'dialCode': '+357', 'currency': 'EUR'},
    {'name': 'Czech Republic', 'code': 'CZ', 'flag': '🇨🇿', 'dialCode': '+420', 'currency': 'CZK'},
    {'name': 'Denmark', 'code': 'DK', 'flag': '🇩🇰', 'dialCode': '+45', 'currency': 'DKK'},
    {'name': 'Djibouti', 'code': 'DJ', 'flag': '🇩🇯', 'dialCode': '+253', 'currency': 'DJF'},
    {'name': 'Dominica', 'code': 'DM', 'flag': '🇩🇲', 'dialCode': '+1767', 'currency': 'XCD'},
    {'name': 'Dominican Republic', 'code': 'DO', 'flag': '🇩🇴', 'dialCode': '+1809', 'currency': 'DOP'},
    {'name': 'Ecuador', 'code': 'EC', 'flag': '🇪🇨', 'dialCode': '+593', 'currency': 'USD'},
    {'name': 'Egypt', 'code': 'EG', 'flag': '🇪🇬', 'dialCode': '+20', 'currency': 'EGP'},
    {'name': 'El Salvador', 'code': 'SV', 'flag': '🇸🇻', 'dialCode': '+503', 'currency': 'USD'},
    {'name': 'Equatorial Guinea', 'code': 'GQ', 'flag': '🇬🇶', 'dialCode': '+240', 'currency': 'XAF'},
    {'name': 'Eritrea', 'code': 'ER', 'flag': '🇪🇷', 'dialCode': '+291', 'currency': 'ERN'},
    {'name': 'Estonia', 'code': 'EE', 'flag': '🇪🇪', 'dialCode': '+372', 'currency': 'EUR'},
    {'name': 'Ethiopia', 'code': 'ET', 'flag': '🇪🇹', 'dialCode': '+251', 'currency': 'ETB'},
    {'name': 'Falkland Islands (Malvinas)', 'code': 'FK', 'flag': '🇫🇰', 'dialCode': '+500', 'currency': 'FKP'},
    {'name': 'Faroe Islands', 'code': 'FO', 'flag': '🇫🇴', 'dialCode': '+298', 'currency': 'DKK'},
    {'name': 'Fiji', 'code': 'FJ', 'flag': '🇫🇯', 'dialCode': '+679', 'currency': 'FJD'},
    {'name': 'Finland', 'code': 'FI', 'flag': '🇫🇮', 'dialCode': '+358', 'currency': 'EUR'},
    {'name': 'France', 'code': 'FR', 'flag': '🇫🇷', 'dialCode': '+33', 'currency': 'EUR'},
    {'name': 'French Guiana', 'code': 'GF', 'flag': '🇫🇷', 'dialCode': '+594', 'currency': 'EUR'},
    {'name': 'French Polynesia', 'code': 'PF', 'flag': '🇵🇫', 'dialCode': '+689', 'currency': 'XPF'},
    {'name': 'French Southern Territories', 'code': 'TF', 'flag': '🇹🇫', 'dialCode': '+262', 'currency': 'EUR'},
    {'name': 'Gabon', 'code': 'GA', 'flag': '🇬🇦', 'dialCode': '+241', 'currency': 'XAF'},
    {'name': 'Gambia', 'code': 'GM', 'flag': '🇬🇲', 'dialCode': '+220', 'currency': 'GMD'},
    {'name': 'Georgia', 'code': 'GE', 'flag': '🇬🇪', 'dialCode': '+995', 'currency': 'GEL'},
    {'name': 'Germany', 'code': 'DE', 'flag': '🇩🇪', 'dialCode': '+49', 'currency': 'EUR'},
    {'name': 'Ghana', 'code': 'GH', 'flag': '🇬🇭', 'dialCode': '+233', 'currency': 'GHS'},
    {'name': 'Gibraltar', 'code': 'GI', 'flag': '🇬🇮', 'dialCode': '+350', 'currency': 'GIP'},
    {'name': 'Greece', 'code': 'GR', 'flag': '🇬🇷', 'dialCode': '+30', 'currency': 'EUR'},
    {'name': 'Greenland', 'code': 'GL', 'flag': '🇬🇱', 'dialCode': '+299', 'currency': 'DKK'},
    {'name': 'Grenada', 'code': 'GD', 'flag': '🇬🇩', 'dialCode': '+1473', 'currency': 'XCD'},
    {'name': 'Guadeloupe', 'code': 'GP', 'flag': '🇬🇵', 'dialCode': '+590', 'currency': 'EUR'},
    {'name': 'Guam', 'code': 'GU', 'flag': '🇬🇺', 'dialCode': '+1671', 'currency': 'USD'},
    {'name': 'Guatemala', 'code': 'GT', 'flag': '🇬🇹', 'dialCode': '+502', 'currency': 'GTQ'},
    {'name': 'Guernsey', 'code': 'GG', 'flag': '🇬🇬', 'dialCode': '+44', 'currency': 'GBP'},
    {'name': 'Guinea', 'code': 'GN', 'flag': '🇬🇳', 'dialCode': '+224', 'currency': 'GNF'},
    {'name': 'Guinea-Bissau', 'code': 'GW', 'flag': '🇬🇼', 'dialCode': '+245', 'currency': 'XOF'},
    {'name': 'Guyana', 'code': 'GY', 'flag': '🇬🇾', 'dialCode': '+592', 'currency': 'GYD'},
    {'name': 'Haiti', 'code': 'HT', 'flag': '🇭🇹', 'dialCode': '+509', 'currency': 'HTG'},
    {'name': 'Heard & McDonald Islands', 'code': 'HM', 'flag': '🇭🇲', 'dialCode': '+672', 'currency': 'AUD'},
    {'name': 'Holy See (Vatican City)', 'code': 'VA', 'flag': '🇻🇦', 'dialCode': '+379', 'currency': 'EUR'},
    {'name': 'Honduras', 'code': 'HN', 'flag': '🇭🇳', 'dialCode': '+504', 'currency': 'HNL'},
    {'name': 'Hong Kong', 'code': 'HK', 'flag': '🇭🇰', 'dialCode': '+852', 'currency': 'HKD'},
    {'name': 'Hungary', 'code': 'HU', 'flag': '🇭🇺', 'dialCode': '+36', 'currency': 'HUF'},
    {'name': 'Iceland', 'code': 'IS', 'flag': '🇮🇸', 'dialCode': '+354', 'currency': 'ISK'},
    {'name': 'India', 'code': 'IN', 'flag': '🇮🇳', 'dialCode': '+91', 'currency': 'INR'},
    {'name': 'Indonesia', 'code': 'ID', 'flag': '🇮🇩', 'dialCode': '+62', 'currency': 'IDR'},
    {'name': 'Iran', 'code': 'IR', 'flag': '🇮🇷', 'dialCode': '+98', 'currency': 'IRR'},
    {'name': 'Iraq', 'code': 'IQ', 'flag': '🇮🇶', 'dialCode': '+964', 'currency': 'IQD'},
    {'name': 'Ireland', 'code': 'IE', 'flag': '🇮🇪', 'dialCode': '+353', 'currency': 'EUR'},
    {'name': 'Isle of Man', 'code': 'IM', 'flag': '🇮🇲', 'dialCode': '+44', 'currency': 'GBP'},
    {'name': 'Israel', 'code': 'IL', 'flag': '🇮🇱', 'dialCode': '+972', 'currency': 'ILS'},
    {'name': 'Italy', 'code': 'IT', 'flag': '🇮🇹', 'dialCode': '+39', 'currency': 'EUR'},
    {'name': 'Jamaica', 'code': 'JM', 'flag': '🇯🇲', 'dialCode': '+1876', 'currency': 'JMD'},
    {'name': 'Japan', 'code': 'JP', 'flag': '🇯🇵', 'dialCode': '+81', 'currency': 'JPY'},
    {'name': 'Jersey', 'code': 'JE', 'flag': '🇯🇪', 'dialCode': '+44', 'currency': 'GBP'},
    {'name': 'Jordan', 'code': 'JO', 'flag': '🇯🇴', 'dialCode': '+962', 'currency': 'JOD'},
    {'name': 'Kazakhstan', 'code': 'KZ', 'flag': '🇰🇿', 'dialCode': '+7', 'currency': 'KZT'},
    {'name': 'Kenya', 'code': 'KE', 'flag': '🇰🇪', 'dialCode': '+254', 'currency': 'KES'},
    {'name': 'Kiribati', 'code': 'KI', 'flag': '🇰🇮', 'dialCode': '+686', 'currency': 'AUD'},
    {'name': 'Korea (North)', 'code': 'KP', 'flag': '🇰🇵', 'dialCode': '+850', 'currency': 'KPW'},
    {'name': 'Korea (South)', 'code': 'KR', 'flag': '🇰🇷', 'dialCode': '+82', 'currency': 'KRW'},
    {'name': 'Kuwait', 'code': 'KW', 'flag': '🇰🇼', 'dialCode': '+965', 'currency': 'KWD'},
    {'name': 'Kyrgyzstan', 'code': 'KG', 'flag': '🇰🇬', 'dialCode': '+996', 'currency': 'KGS'},
    {'name': 'Laos', 'code': 'LA', 'flag': '🇱🇦', 'dialCode': '+856', 'currency': 'LAK'},
    {'name': 'Latvia', 'code': 'LV', 'flag': '🇱🇻', 'dialCode': '+371', 'currency': 'EUR'},
    {'name': 'Lebanon', 'code': 'LB', 'flag': '🇱🇧', 'dialCode': '+961', 'currency': 'LBP'},
    {'name': 'Lesotho', 'code': 'LS', 'flag': '🇱🇸', 'dialCode': '+266', 'currency': 'LSL'},
    {'name': 'Liberia', 'code': 'LR', 'flag': '🇱🇷', 'dialCode': '+231', 'currency': 'LRD'},
    {'name': 'Libya', 'code': 'LY', 'flag': '🇱🇾', 'dialCode': '+218', 'currency': 'LYD'},
    {'name': 'Liechtenstein', 'code': 'LI', 'flag': '🇱🇮', 'dialCode': '+423', 'currency': 'CHF'},
    {'name': 'Lithuania', 'code': 'LT', 'flag': '🇱🇹', 'dialCode': '+370', 'currency': 'EUR'},
    {'name': 'Luxembourg', 'code': 'LU', 'flag': '🇱🇺', 'dialCode': '+352', 'currency': 'EUR'},
    {'name': 'Macau', 'code': 'MO', 'flag': '🇲🇴', 'dialCode': '+853', 'currency': 'MOP'},
    {'name': 'Macedonia (North)', 'code': 'MK', 'flag': '🇲🇰', 'dialCode': '+389', 'currency': 'MKD'},
    {'name': 'Madagascar', 'code': 'MG', 'flag': '🇲🇬', 'dialCode': '+261', 'currency': 'MGA'},
    {'name': 'Malawi', 'code': 'MW', 'flag': '🇲🇼', 'dialCode': '+265', 'currency': 'MWK'},
    {'name': 'Malaysia', 'code': 'MY', 'flag': '🇲🇾', 'dialCode': '+60', 'currency': 'MYR'},
    {'name': 'Maldives', 'code': 'MV', 'flag': '🇲🇻', 'dialCode': '+960', 'currency': 'MVR'},
    {'name': 'Mali', 'code': 'ML', 'flag': '🇲🇱', 'dialCode': '+223', 'currency': 'XOF'},
    {'name': 'Malta', 'code': 'MT', 'flag': '🇲🇹', 'dialCode': '+356', 'currency': 'EUR'},
    {'name': 'Marshall Islands', 'code': 'MH', 'flag': '🇲🇭', 'dialCode': '+692', 'currency': 'USD'},
    {'name': 'Martinique', 'code': 'MQ', 'flag': '🇲🇶', 'dialCode': '+596', 'currency': 'EUR'},
    {'name': 'Mauritania', 'code': 'MR', 'flag': '🇲🇷', 'dialCode': '+222', 'currency': 'MRU'},
    {'name': 'Mauritius', 'code': 'MU', 'flag': '🇲🇺', 'dialCode': '+230', 'currency': 'MUR'},
    {'name': 'Mayotte', 'code': 'YT', 'flag': '🇾🇹', 'dialCode': '+262', 'currency': 'EUR'},
    {'name': 'Mexico', 'code': 'MX', 'flag': '🇲🇽', 'dialCode': '+52', 'currency': 'MXN'},
    {'name': 'Micronesia', 'code': 'FM', 'flag': '🇫🇲', 'dialCode': '+691', 'currency': 'USD'},
    {'name': 'Moldova', 'code': 'MD', 'flag': '🇲🇩', 'dialCode': '+373', 'currency': 'MDL'},
    {'name': 'Monaco', 'code': 'MC', 'flag': '🇲🇨', 'dialCode': '+377', 'currency': 'EUR'},
    {'name': 'Mongolia', 'code': 'MN', 'flag': '🇲🇳', 'dialCode': '+976', 'currency': 'MNT'},
    {'name': 'Montenegro', 'code': 'ME', 'flag': '🇲🇪', 'dialCode': '+382', 'currency': 'EUR'},
    {'name': 'Montserrat', 'code': 'MS', 'flag': '🇲🇸', 'dialCode': '+1664', 'currency': 'XCD'},
    {'name': 'Morocco', 'code': 'MA', 'flag': '🇲🇦', 'dialCode': '+212', 'currency': 'MAD'},
    {'name': 'Mozambique', 'code': 'MZ', 'flag': '🇲🇿', 'dialCode': '+258', 'currency': 'MZN'},
    {'name': 'Myanmar (Burma)', 'code': 'MM', 'flag': '🇲🇲', 'dialCode': '+95', 'currency': 'MMK'},
    {'name': 'Namibia', 'code': 'NA', 'flag': '🇳🇦', 'dialCode': '+264', 'currency': 'NAD'},
    {'name': 'Nauru', 'code': 'NR', 'flag': '🇳🇷', 'dialCode': '+674', 'currency': 'AUD'},
    {'name': 'Nepal', 'code': 'NP', 'flag': '🇳🇵', 'dialCode': '+977', 'currency': 'NPR'},
    {'name': 'Netherlands', 'code': 'NL', 'flag': '🇳🇱', 'dialCode': '+31', 'currency': 'EUR'},
    {'name': 'New Caledonia', 'code': 'NC', 'flag': '🇳🇨', 'dialCode': '+687', 'currency': 'XPF'},
    {'name': 'New Zealand', 'code': 'NZ', 'flag': '🇳🇿', 'dialCode': '+64', 'currency': 'NZD'},
    {'name': 'Nicaragua', 'code': 'NI', 'flag': '🇳🇮', 'dialCode': '+505', 'currency': 'NIO'},
    {'name': 'Niger', 'code': 'NE', 'flag': '🇳🇪', 'dialCode': '+227', 'currency': 'XOF'},
    {'name': 'Nigeria', 'code': 'NG', 'flag': '🇳🇬', 'dialCode': '+234', 'currency': 'NGN'},
    {'name': 'Niue', 'code': 'NU', 'flag': '🇳🇺', 'dialCode': '+683', 'currency': 'NZD'},
    {'name': 'Norfolk Island', 'code': 'NF', 'flag': '🇳🇫', 'dialCode': '+672', 'currency': 'AUD'},
    {'name': 'Northern Mariana Islands', 'code': 'MP', 'flag': '🇲🇵', 'dialCode': '+1670', 'currency': 'USD'},
    {'name': 'Norway', 'code': 'NO', 'flag': '🇳🇴', 'dialCode': '+47', 'currency': 'NOK'},
    {'name': 'Oman', 'code': 'OM', 'flag': '🇴🇲', 'dialCode': '+968', 'currency': 'OMR'},
    {'name': 'Pakistan', 'code': 'PK', 'flag': '🇵🇰', 'dialCode': '+92', 'currency': 'PKR'},
    {'name': 'Palau', 'code': 'PW', 'flag': '🇵🇼', 'dialCode': '+680', 'currency': 'USD'},
    {'name': 'Palestine', 'code': 'PS', 'flag': '🇵🇸', 'dialCode': '+970', 'currency': 'ILS'},
    {'name': 'Panama', 'code': 'PA', 'flag': '🇵🇦', 'dialCode': '+507', 'currency': 'PAB'},
    {'name': 'Papua New Guinea', 'code': 'PG', 'flag': '🇵🇬', 'dialCode': '+675', 'currency': 'PGK'},
    {'name': 'Paraguay', 'code': 'PY', 'flag': '🇵🇾', 'dialCode': '+595', 'currency': 'PYG'},
    {'name': 'Peru', 'code': 'PE', 'flag': '🇵🇪', 'dialCode': '+51', 'currency': 'PEN'},
    {'name': 'Philippines', 'code': 'PH', 'flag': '🇵🇭', 'dialCode': '+63', 'currency': 'PHP'},
    {'name': 'Pitcairn', 'code': 'PN', 'flag': '🇵🇳', 'dialCode': '+64', 'currency': 'NZD'},
    {'name': 'Poland', 'code': 'PL', 'flag': '🇵🇱', 'dialCode': '+48', 'currency': 'PLN'},
    {'name': 'Portugal', 'code': 'PT', 'flag': '🇵🇹', 'dialCode': '+351', 'currency': 'EUR'},
    {'name': 'Puerto Rico', 'code': 'PR', 'flag': '🇵🇷', 'dialCode': '+1787', 'currency': 'USD'},
    {'name': 'Qatar', 'code': 'QA', 'flag': '🇶🇦', 'dialCode': '+974', 'currency': 'QAR'},
    {'name': 'Réunion', 'code': 'RE', 'flag': '🇷🇪', 'dialCode': '+262', 'currency': 'EUR'},
    {'name': 'Romania', 'code': 'RO', 'flag': '🇷🇴', 'dialCode': '+40', 'currency': 'RON'},
    {'name': 'Russia', 'code': 'RU', 'flag': '🇷🇺', 'dialCode': '+7', 'currency': 'RUB'},
    {'name': 'Rwanda', 'code': 'RW', 'flag': '🇷🇼', 'dialCode': '+250', 'currency': 'RWF'},
    {'name': 'Saint Barthélemy', 'code': 'BL', 'flag': '🇧🇱', 'dialCode': '+590', 'currency': 'EUR'},
    {'name': 'Saint Helena', 'code': 'SH', 'flag': '🇸🇭', 'dialCode': '+290', 'currency': 'SHP'},
    {'name': 'Saint Kitts & Nevis', 'code': 'KN', 'flag': '🇰🇳', 'dialCode': '+1869', 'currency': 'XCD'},
    {'name': 'Saint Lucia', 'code': 'LC', 'flag': '🇱🇨', 'dialCode': '+1758', 'currency': 'XCD'},
    {'name': 'Saint Martin', 'code': 'MF', 'flag': '🇲🇫', 'dialCode': '+590', 'currency': 'EUR'},
    {'name': 'Saint Pierre & Miquelon', 'code': 'PM', 'flag': '🇵🇲', 'dialCode': '+508', 'currency': 'EUR'},
    {'name': 'Saint Vincent & Grenadines', 'code': 'VC', 'flag': '🇻🇨', 'dialCode': '+1784', 'currency': 'XCD'},
    {'name': 'Samoa', 'code': 'WS', 'flag': '🇼🇸', 'dialCode': '+685', 'currency': 'WST'},
    {'name': 'San Marino', 'code': 'SM', 'flag': '🇸🇲', 'dialCode': '+378', 'currency': 'EUR'},
    {'name': 'Sao Tome & Principe', 'code': 'ST', 'flag': '🇸🇹', 'dialCode': '+239', 'currency': 'STN'},
    {'name': 'Saudi Arabia', 'code': 'SA', 'flag': '🇸🇦', 'dialCode': '+966', 'currency': 'SAR'},
    {'name': 'Senegal', 'code': 'SN', 'flag': '🇸🇳', 'dialCode': '+221', 'currency': 'XOF'},
    {'name': 'Serbia', 'code': 'RS', 'flag': '🇷🇸', 'dialCode': '+381', 'currency': 'RSD'},
    {'name': 'Seychelles', 'code': 'SC', 'flag': '🇸🇨', 'dialCode': '+248', 'currency': 'SCR'},
    {'name': 'Sierra Leone', 'code': 'SL', 'flag': '🇸🇱', 'dialCode': '+232', 'currency': 'SLL'},
    {'name': 'Singapore', 'code': 'SG', 'flag': '🇸🇬', 'dialCode': '+65', 'currency': 'SGD'},
    {'name': 'Sint Maarten', 'code': 'SX', 'flag': '🇸🇽', 'dialCode': '+1721', 'currency': 'ANG'},
    {'name': 'Slovakia', 'code': 'SK', 'flag': '🇸🇰', 'dialCode': '+421', 'currency': 'EUR'},
    {'name': 'Slovenia', 'code': 'SI', 'flag': '🇸🇮', 'dialCode': '+386', 'currency': 'EUR'},
    {'name': 'Solomon Islands', 'code': 'SB', 'flag': '🇸🇧', 'dialCode': '+677', 'currency': 'SBD'},
    {'name': 'Somalia', 'code': 'SO', 'flag': '🇸🇴', 'dialCode': '+252', 'currency': 'SOS'},
    {'name': 'South Africa', 'code': 'ZA', 'flag': '🇿🇦', 'dialCode': '+27', 'currency': 'ZAR'},
    {'name': 'South Georgia & Sandwich Is.', 'code': 'GS', 'flag': '🇬🇸', 'dialCode': '+500', 'currency': 'GBP'},
    {'name': 'South Sudan', 'code': 'SS', 'flag': '🇸🇸', 'dialCode': '+211', 'currency': 'SSP'},
    {'name': 'Spain', 'code': 'ES', 'flag': '🇪🇸', 'dialCode': '+34', 'currency': 'EUR'},
    {'name': 'Sri Lanka', 'code': 'LK', 'flag': '🇱🇰', 'dialCode': '+94', 'currency': 'LKR'},
    {'name': 'Sudan', 'code': 'SD', 'flag': '🇸🇩', 'dialCode': '+249', 'currency': 'SDG'},
    {'name': 'Suriname', 'code': 'SR', 'flag': '🇸🇷', 'dialCode': '+597', 'currency': 'SRD'},
    {'name': 'Svalbard & Jan Mayen', 'code': 'SJ', 'flag': '🇸🇯', 'dialCode': '+47', 'currency': 'NOK'},
    {'name': 'Eswatini (Swaziland)', 'code': 'SZ', 'flag': '🇸🇿', 'dialCode': '+268', 'currency': 'SZL'},
    {'name': 'Sweden', 'code': 'SE', 'flag': '🇸🇪', 'dialCode': '+46', 'currency': 'SEK'},
    {'name': 'Switzerland', 'code': 'CH', 'flag': '🇨🇭', 'dialCode': '+41', 'currency': 'CHF'},
    {'name': 'Syria', 'code': 'SY', 'flag': '🇸🇾', 'dialCode': '+963', 'currency': 'SYP'},
    {'name': 'Taiwan', 'code': 'TW', 'flag': '🇹🇼', 'dialCode': '+886', 'currency': 'TWD'},
    {'name': 'Tajikistan', 'code': 'TJ', 'flag': '🇹🇯', 'dialCode': '+992', 'currency': 'TJS'},
    {'name': 'Tanzania', 'code': 'TZ', 'flag': '🇹🇿', 'dialCode': '+255', 'currency': 'TZS'},
    {'name': 'Thailand', 'code': 'TH', 'flag': '🇹🇭', 'dialCode': '+66', 'currency': 'THB'},
    {'name': 'Timor-Leste', 'code': 'TL', 'flag': '🇹🇱', 'dialCode': '+670', 'currency': 'USD'},
    {'name': 'Togo', 'code': 'TG', 'flag': '🇹🇬', 'dialCode': '+228', 'currency': 'XOF'},
    {'name': 'Tokelau', 'code': 'TK', 'flag': '🇹🇰', 'dialCode': '+690', 'currency': 'NZD'},
    {'name': 'Tonga', 'code': 'TO', 'flag': '🇹🇴', 'dialCode': '+676', 'currency': 'TOP'},
    {'name': 'Trinidad & Tobago', 'code': 'TT', 'flag': '🇹🇹', 'dialCode': '+1868', 'currency': 'TTD'},
    {'name': 'Tunisia', 'code': 'TN', 'flag': '🇹🇳', 'dialCode': '+216', 'currency': 'TND'},
    {'name': 'Turkey', 'code': 'TR', 'flag': '🇹🇷', 'dialCode': '+90', 'currency': 'TRY'},
    {'name': 'Turkmenistan', 'code': 'TM', 'flag': '🇹🇲', 'dialCode': '+993', 'currency': 'TMT'},
    {'name': 'Turks & Caicos Islands', 'code': 'TC', 'flag': '🇹🇨', 'dialCode': '+1649', 'currency': 'USD'},
    {'name': 'Tuvalu', 'code': 'TV', 'flag': '🇹🇻', 'dialCode': '+688', 'currency': 'AUD'},
    {'name': 'Uganda', 'code': 'UG', 'flag': '🇺🇬', 'dialCode': '+256', 'currency': 'UGX'},
    {'name': 'Ukraine', 'code': 'UA', 'flag': '🇺🇦', 'dialCode': '+380', 'currency': 'UAH'},
    {'name': 'United Arab Emirates', 'code': 'AE', 'flag': '🇦🇪', 'dialCode': '+971', 'currency': 'AED'},
    {'name': 'United Kingdom', 'code': 'GB', 'flag': '🇬🇧', 'dialCode': '+44', 'currency': 'GBP'},
    {'name': 'United States', 'code': 'US', 'flag': '🇺🇸', 'dialCode': '+1', 'currency': 'USD'},
    {'name': 'United States Minor Outlying Is.', 'code': 'UM', 'flag': '🇺🇲', 'dialCode': '+1', 'currency': 'USD'},
    {'name': 'Uruguay', 'code': 'UY', 'flag': '🇺🇾', 'dialCode': '+598', 'currency': 'UYU'},
    {'name': 'Uzbekistan', 'code': 'UZ', 'flag': '🇺🇿', 'dialCode': '+998', 'currency': 'UZS'},
    {'name': 'Vanuatu', 'code': 'VU', 'flag': '🇻🇺', 'dialCode': '+678', 'currency': 'VUV'},
    {'name': 'Venezuela', 'code': 'VE', 'flag': '🇻🇪', 'dialCode': '+58', 'currency': 'VES'},
    {'name': 'Vietnam', 'code': 'VN', 'flag': '🇻🇳', 'dialCode': '+84', 'currency': 'VND'},
    {'name': 'British Virgin Islands', 'code': 'VG', 'flag': '🇻🇬', 'dialCode': '+1284', 'currency': 'USD'},
    {'name': 'U.S. Virgin Islands', 'code': 'VI', 'flag': '🇻🇮', 'dialCode': '+1340', 'currency': 'USD'},
    {'name': 'Wallis & Futuna', 'code': 'WF', 'flag': '🇼🇫', 'dialCode': '+681', 'currency': 'XPF'},
    {'name': 'Western Sahara', 'code': 'EH', 'flag': '🇪🇭', 'dialCode': '+212', 'currency': 'MAD'},
    {'name': 'Yemen', 'code': 'YE', 'flag': '🇾🇪', 'dialCode': '+967', 'currency': 'YER'},
    {'name': 'Zambia', 'code': 'ZM', 'flag': '🇿🇲', 'dialCode': '+260', 'currency': 'ZMW'},
    {'name': 'Zimbabwe', 'code': 'ZW', 'flag': '🇿🇼', 'dialCode': '+263', 'currency': 'ZWL'},
  ];

  /// Map of currency code → symbol.
  static const Map<String, String> currencySymbols = {
    'USD': '\$',
    'EUR': '€',
    'GBP': '£',
    'NGN': '₦',
    'JPY': '¥',
    'CNY': '¥',
    'KRW': '₩',
    'INR': '₹',
    'RUB': '₽',
    'BRL': 'R\$',
    'CHF': 'Fr',
    'SEK': 'kr',
    'NOK': 'kr',
    'DKK': 'kr',
    'ISK': 'kr',
    'PLN': 'zł',
    'CZK': 'Kč',
    'HUF': 'Ft',
    'RON': 'lei',
    'BGN': 'лв',
    'TRY': '₺',
    'UAH': '₴',
    'THB': '฿',
    'IDR': 'Rp',
    'MYR': 'RM',
    'PHP': '₱',
    'VND': '₫',
    'SGD': 'S\$',
    'HKD': 'HK\$',
    'TWD': 'NT\$',
    'AUD': 'A\$',
    'NZD': 'NZ\$',
    'CAD': 'C\$',
    'MXN': '\$',
    'ARS': '\$',
    'CLP': '\$',
    'COP': '\$',
    'PEN': 'S/',
    'UYU': '\$U',
    'ZAR': 'R',
    'EGP': 'E£',
    'MAD': 'DH',
    'TND': 'DT',
    'DZD': 'DA',
    'LYD': 'LD',
    'SAR': 'SR',
    'AED': 'AED',
    'QAR': 'QR',
    'KWD': 'KD',
    'BHD': 'BD',
    'OMR': 'OMR',
    'JOD': 'JD',
    'LBP': 'L£',
    'ILS': '₪',
    'IRR': '﷼',
    'IQD': 'ع.د',
    'PKR': 'Rs',
    'BDT': '৳',
    'LKR': 'Rs',
    'NPR': 'Rs',
    'AFN': '؋',
    'KZT': '₸',
    'UZS': 'so\'m',
    'AZN': '₼',
    'GEL': '₾',
    'AMD': '֏',
    'BYN': 'Br',
    'KGS': 'som',
    'TJS': 'ЅМ',
    'TMT': 'm',
    'MNT': '₮',
    'KHR': '៛',
    'LAK': '₭',
    'MMK': 'K',
    'VUV': 'Vt',
    'FJD': 'FJ\$',
    'PGK': 'K',
    'SBD': 'SI\$',
    'WST': 'WS\$',
    'TOP': 'T\$',
    'KES': 'KSh',
    'UGX': 'USh',
    'TZS': 'TSh',
    'GHS': '₵',
    'ETB': 'Br',
    'RWF': 'FRw',
    'XOF': 'CFA',
    'XAF': 'FCFA',
    'XPF': '₣',
    'XCD': 'EC\$',
    'ANG': 'ƒ',
    'AWG': 'ƒ',
    'HNL': 'L',
    'GTQ': 'Q',
    'NIC': 'C\$',
    'CRC': '₡',
    'PAB': 'B/',
    'DOP': 'RD\$',
    'HTG': 'G',
    'CUP': '₱',
    'JMD': 'J\$',
    'TTD': 'TT\$',
    'BBD': 'Bds\$',
    'BSD': 'B\$',
    'BZD': 'BZ\$',
    'GYD': 'G\$',
    'SRD': 'Sr\$',
    'PYG': '₲',
    'BOB': 'Bs',
    'VEF': 'Bs',
    'VES': 'Bs',
    'GIP': '£',
    'FKP': '£',
    'SHP': '£',
    'SSP': '£',
    'SLL': 'Le',
    'LRD': 'L\$',
    'MOP': 'MOP\$',
    'BND': 'B\$',
    'MVR': 'Rf',
    'BIF': 'FBu',
    'KMF': 'CF',
    'DJF': 'Fdj',
    'ERN': 'Nfk',
    'SOS': 'Sh',
    'MWK': 'MK',
    'ZMW': 'ZK',
    'ZWL': 'Z\$',
    'MZN': 'MT',
    'AOA': 'Kz',
    'MGA': 'Ar',
    'MRU': 'UM',
    'STN': 'Db',
    'SCR': 'SR',
    'MUR': 'Rs',
    'LSL': 'L',
    'SZL': 'L',
    'NAD': 'N\$',
    'BWP': 'P',
  };

  /// Get the symbol for a currency code, falling back to the code itself.
  static String currencySymbol(String code) {
    return currencySymbols[code] ?? code;
  }

  /// Get the currency code for a country name.
  static String currencyForCountry(String? countryName) {
    if (countryName == null) return 'NGN';
    final match = all.where((c) => c['name'] == countryName);
    return match.isNotEmpty ? match.first['currency']! : 'NGN';
  }
}
